export type CustomerStatus =
  | "new"
  | "call_scheduled"
  | "calling"
  | "contacted"
  | "appointment_set"
  | "follow_up"
  | "no_answer"
  | "not_interested"
  | "do_not_call";

export type AppointmentStatus =
  | "scheduled"
  | "confirmed"
  | "completed"
  | "canceled"
  | "no_show";

export type CallOutcome =
  | "appointment_set"
  | "no_answer"
  | "voicemail"
  | "not_interested"
  | "call_back_later"
  | "error"
  | null;

/** Live state of the Vapi call, mirrored so the portal can cancel/hang up. */
export type CallStatus =
  | "scheduled"
  | "queued"
  | "ringing"
  | "in_progress"
  | "ended"
  | "canceled"
  | "failed";

/** Statuses where a call hasn't finished yet, so it can still be canceled. */
export const LIVE_CALL_STATUSES = [
  "scheduled",
  "queued",
  "ringing",
  "in_progress",
] as const satisfies readonly CallStatus[];

/** Which script a customer's call follows. Mirrors SalesAgent.default_script — see 00000000000015_agent_ai_integration_defaults.sql. */
export type CallType = "POS" | "UNION" | "WILL_KIT";

export const CALL_TYPES = [
  "POS",
  "UNION",
  "WILL_KIT",
] as const satisfies readonly CallType[];

export type AgentRole = "agent" | "admin";

/** Where a self-registered agent sits in the admin's approval queue. */
export type ApprovalStatus = "pending" | "approved" | "rejected";

// NB: these are `type`, not `interface` — postgrest-js's generic type
// resolution (ParseQuery / Simplify chains) fails to match interface types
// here and silently collapses query results to `never`. Keep these as type
// aliases even though interfaces would normally be preferred.

export type Customer = {
  id: string;
  name: string;
  phone: string;
  email: string | null;
  status: CustomerStatus;
  agent_id: string | null;
  company: string | null;
  notes: string | null;
  timezone: string | null;
  last_contacted_at: string | null;
  /** Will-kit campaign: what the lead told us when they requested the kit.
   * Riley only states these back on a call when they're actually set. */
  province: string | null;
  kit_count: number | null;
  mailing_address: string | null;
  /** Date only (YYYY-MM-DD) — when the online request came in. */
  request_date: string | null;
  /** Date only (YYYY-MM-DD). Confirmed by Abby near the top of the call. */
  date_of_birth: string | null;
  /** Confirmed by Abby near the top of the call. */
  beneficiary_name: string | null;
  /** Read out during the write-down close; generated by the database. */
  confirmation_code: string | null;
  spouse_name: string | null;
  employment_status: string | null;
  household_type: string | null;
  preferred_meeting_time: string | null;
  follow_up_at: string | null;
  call_insights: Record<string, unknown> | null;
  last_call_summary: string | null;
  /** How many auto-retry calls have been placed since the last non-retry outcome. */
  retry_count: number;
  /** When the auto-retry cron (app/api/cron/process-retries) should next dial this customer, or null if none is armed. */
  next_retry_at: string | null;
  /** Which auto-dial campaign's calling window next_retry_at was clamped into — carried forward into the retry call so the same window applies next time too. */
  retry_campaign_id: string | null;
  /** Which script Riley should follow on this customer's call. Null on customers created before this field existed. */
  call_type: CallType | null;
  created_at: string;
};

export type CustomerWithAgent = Customer & {
  agent: Pick<SalesAgent, "id" | "name" | "email"> | null;
};

export type SalesAgent = {
  id: string;
  name: string;
  email: string;
  role: AgentRole;
  is_active: boolean;
  approval_status: ApprovalStatus;
  approved_at: string | null;
  approved_by: string | null;
  rejection_reason: string | null;
  auth_user_id: string | null;
  phone: string | null;
  timezone: string;
  calendly_url: string | null;
  calendly_access_token: string | null;
  calendly_refresh_token: string | null;
  calendly_user_uri: string | null;
  calendly_webhook_uri: string | null;
  calendly_webhook_signing_key: string | null;
  /** @deprecated superseded by agent_phone_numbers — an agent can connect several. */
  vapi_phone_number_id: string | null;
  /** @deprecated superseded by agent_phone_numbers — an agent can connect several. */
  vapi_phone_number: string | null;
  /** @deprecated superseded by agent_phone_numbers — an agent can connect several. */
  twilio_phone_number_sid: string | null;
  /** Set on the AI Integration page. Pre-fills the voice pick on Call panel/list/campaigns; still overridable per call. */
  default_voice_gender: "male" | "female" | null;
  /** Set on the AI Integration page. Storage only for now — POS is the only script vapi/agent.md actually implements. */
  default_script: "POS" | "UNION" | "WILL_KIT" | null;
  /** Minutes to wait before auto-redialing a follow_up/no_answer customer. */
  retry_delay_minutes: number;
  /** How many auto-retry calls to place before giving up and leaving the customer for a human to redial. */
  retry_max_attempts: number;
  created_at: string;
};

/** One outbound number an agent has connected — an agent may have several. */
export type AgentPhoneNumber = {
  id: string;
  agent_id: string;
  phone_number: string;
  twilio_phone_number_sid: string;
  vapi_phone_number_id: string;
  created_at: string;
};

/** Maps one of the 7 fixed Canadian regions (or "default") to a connected number — see lib/area-code-routing.ts. */
export type AgentNumberRoute = {
  id: string;
  agent_id: string;
  region: string;
  phone_number_id: string;
  created_at: string;
};

export type Appointment = {
  id: string;
  customer_id: string;
  agent_id: string | null;
  scheduled_at: string;
  duration_minutes: number;
  zoom_link: string | null;
  calendly_event_uri: string | null;
  booking_url: string | null;
  cancel_url: string | null;
  reschedule_url: string | null;
  source: "voice_agent" | "manual";
  notes: string | null;
  canceled_reason: string | null;
  canceled_at: string | null;
  status: AppointmentStatus;
  created_at: string;
  updated_at: string;
};

export type AppointmentWithRelations = Appointment & {
  customer: Pick<Customer, "id" | "name" | "phone" | "email"> | null;
  agent: Pick<SalesAgent, "id" | "name" | "email"> | null;
};

export type Call = {
  id: string;
  customer_id: string;
  agent_id: string | null;
  vapi_call_id: string | null;
  status: CallStatus;
  control_url: string | null;
  ended_reason: string | null;
  duration_seconds: number | null;
  cost: number | null;
  summary: string | null;
  scheduled_for: string | null;
  canceled_at: string | null;
  triggered_by: string | null;
  transcript: string | null;
  recording_url: string | null;
  outcome: CallOutcome;
  campaign_id: string | null;
  call_insights: Record<string, unknown> | null;
  /** Which connected number actually placed this call — resolved by area-code region routing. */
  phone_number_id: string | null;
  created_at: string;
};

export type CallWithRelations = Call & {
  customer: Pick<Customer, "id" | "name" | "phone"> | null;
  agent: Pick<SalesAgent, "id" | "name"> | null;
};

export type CampaignStatus =
  | "draft"
  | "scheduled"
  | "running"
  | "paused"
  | "stopped"
  | "completed";

export type DialCampaign = {
  id: string;
  agent_id: string;
  status: CampaignStatus;
  window_start: string;
  window_end: string;
  gap_seconds: number;
  current_customer_id: string | null;
  /** @deprecated each call now resolves its own number via area-code region routing (lib/number-routing.ts). */
  phone_number_id: string | null;
  /** Picked once when the agent starts the campaign; every call it places uses this voice. */
  voice_gender: "male" | "female" | null;
  created_at: string;
  updated_at: string;
};

export type DialCampaignCustomer = {
  id: string;
  campaign_id: string;
  customer_id: string;
  sort_order: number;
  status: "pending" | "dialing" | "completed" | "skipped";
};

/** One row per change made on the AI Integration page — powers its "recent changes" history. */
export type AgentAiPreferenceChange = {
  id: string;
  agent_id: string;
  field: "voice_gender" | "script";
  old_value: string | null;
  new_value: string | null;
  changed_at: string;
};

export type InboundCallStatus = "rejected" | "missed";

export type InboundCall = {
  id: string;
  agent_id: string | null;
  vapi_phone_number_id: string | null;
  called_number: string;
  caller_phone: string;
  caller_name: string | null;
  vapi_call_id: string | null;
  is_repeat: boolean;
  repeat_count: number;
  status: InboundCallStatus;
  created_at: string;
};

export type Database = {
  public: {
    Tables: {
      customers: {
        Row: Customer;
        Insert: Partial<Customer> & Pick<Customer, "name" | "phone">;
        Update: Partial<Customer>;
        Relationships: [
          {
            foreignKeyName: "customers_agent_id_fkey";
            columns: ["agent_id"];
            isOneToOne: false;
            referencedRelation: "sales_agents";
            referencedColumns: ["id"];
          },
        ];
      };
      sales_agents: {
        Row: SalesAgent;
        Insert: Partial<SalesAgent> & Pick<SalesAgent, "name" | "email">;
        Update: Partial<SalesAgent>;
        Relationships: [];
      };
      appointments: {
        Row: Appointment;
        Insert: Partial<Appointment> &
          Pick<Appointment, "customer_id" | "scheduled_at">;
        Update: Partial<Appointment>;
        Relationships: [
          {
            foreignKeyName: "appointments_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "appointments_agent_id_fkey";
            columns: ["agent_id"];
            isOneToOne: false;
            referencedRelation: "sales_agents";
            referencedColumns: ["id"];
          },
        ];
      };
      calls: {
        Row: Call;
        Insert: Partial<Call> & Pick<Call, "customer_id">;
        Update: Partial<Call>;
        Relationships: [
          {
            foreignKeyName: "calls_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "calls_agent_id_fkey";
            columns: ["agent_id"];
            isOneToOne: false;
            referencedRelation: "sales_agents";
            referencedColumns: ["id"];
          },
        ];
      };
      dial_campaigns: {
        Row: DialCampaign;
        Insert: Partial<DialCampaign> &
          Pick<DialCampaign, "agent_id" | "window_start" | "window_end">;
        Update: Partial<DialCampaign>;
        Relationships: [
          {
            foreignKeyName: "dial_campaigns_agent_id_fkey";
            columns: ["agent_id"];
            isOneToOne: false;
            referencedRelation: "sales_agents";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "dial_campaigns_phone_number_id_fkey";
            columns: ["phone_number_id"];
            isOneToOne: false;
            referencedRelation: "agent_phone_numbers";
            referencedColumns: ["id"];
          },
        ];
      };
      agent_phone_numbers: {
        Row: AgentPhoneNumber;
        Insert: Partial<AgentPhoneNumber> &
          Pick<AgentPhoneNumber, "agent_id" | "phone_number" | "twilio_phone_number_sid" | "vapi_phone_number_id">;
        Update: Partial<AgentPhoneNumber>;
        Relationships: [
          {
            foreignKeyName: "agent_phone_numbers_agent_id_fkey";
            columns: ["agent_id"];
            isOneToOne: false;
            referencedRelation: "sales_agents";
            referencedColumns: ["id"];
          },
        ];
      };
      agent_number_routes: {
        Row: AgentNumberRoute;
        Insert: Partial<AgentNumberRoute> &
          Pick<AgentNumberRoute, "agent_id" | "region" | "phone_number_id">;
        Update: Partial<AgentNumberRoute>;
        Relationships: [
          {
            foreignKeyName: "agent_number_routes_agent_id_fkey";
            columns: ["agent_id"];
            isOneToOne: false;
            referencedRelation: "sales_agents";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "agent_number_routes_phone_number_id_fkey";
            columns: ["phone_number_id"];
            isOneToOne: false;
            referencedRelation: "agent_phone_numbers";
            referencedColumns: ["id"];
          },
        ];
      };
      dial_campaign_customers: {
        Row: DialCampaignCustomer;
        Insert: Partial<DialCampaignCustomer> &
          Pick<DialCampaignCustomer, "campaign_id" | "customer_id">;
        Update: Partial<DialCampaignCustomer>;
        Relationships: [];
      };
      agent_ai_preference_changes: {
        Row: AgentAiPreferenceChange;
        Insert: Partial<AgentAiPreferenceChange> &
          Pick<AgentAiPreferenceChange, "agent_id" | "field">;
        Update: Partial<AgentAiPreferenceChange>;
        Relationships: [
          {
            foreignKeyName: "agent_ai_preference_changes_agent_id_fkey";
            columns: ["agent_id"];
            isOneToOne: false;
            referencedRelation: "sales_agents";
            referencedColumns: ["id"];
          },
        ];
      };
      inbound_calls: {
        Row: InboundCall;
        Insert: Partial<InboundCall> &
          Pick<InboundCall, "called_number" | "caller_phone">;
        Update: Partial<InboundCall>;
        Relationships: [
          {
            foreignKeyName: "inbound_calls_agent_id_fkey";
            columns: ["agent_id"];
            isOneToOne: false;
            referencedRelation: "sales_agents";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
